// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltonzaicpxzsrzfnqwxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0b256YWljcHh6c3J6Zm5xd3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDc5MTcsImV4cCI6MjA2Nzg4MzkxN30.mwjwfnDw6mQ1xO8mb6yZEGUKhWguwRszVWtp8gGNBpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});